### PR TITLE
Update Kubernetes client and dependency check version

### PR DESCRIPTION
**Pull request by sluehr**
Also introduces example configuration suitable for running in Minikube.

### CODE REVIEW

**Comment by ywangd** [comment]
I think it feels weird to have all these minikube deployment files sit under `doc`. They worth their own top level sub-folder imo, i.e. have `minikube` dir to be at the same level as `doc`.

**Comment by sluehr** [comment]
> I think it feels weird to have all these minikube deployment files sit under `doc`. They worth their own top level sub-folder imo, i.e. have `minikube` dir to be at the same level as `doc`.

I agree but held off as the root directory is getting rather crowded.

How about moving 'minikube' up to the root while move all the Gradle subprojects into a 'src' directory?

**Comment by sluehr** [comment]
See if the latest commit works for you :)

**Review by ywangd — APPROVED** [review]
LGTM

**Pull request merged**
